<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BahankajianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Bahankajian::insert([
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Akidah',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Analisis Keuangan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Analisis Solusi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Business Feasibility Study',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Dasar Negara',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Demokrasi Pancasila',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'English Communication',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'English Conversation',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'English Listening',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'English Writing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Etika',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Etika Diskusi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Experimental Analysis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Fiqih',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Gramatika',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Hak dan Kewajiban Warga Negara',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'HKI',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Identitas Nasional',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Karakter Kepemimpinan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Kepribadian Positif',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Kerjasama Tim',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Komunikasi Bisnis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Komunikasi Interpersonal',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Komunikasi Organisasi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Konsep Komunikasi Publik',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Manajemen Produksi dan Operasional',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Manajemen Sumber Daya',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Muamalah',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Pemahaman Lingkungan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Pemahaman Permasalahan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Pemasaran',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Penampilan Diri dan Teknik Bicara',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Persiapan Materi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Presentation Technique',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Profesionalisme Kerja',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Publication Ethics',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Research Methodology',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Sejarah Peradaban Islam',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [

                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Study Literature',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'Supremasi Hukum',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Kajian Umum",
                'bahankajian' => 'System Design',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Algoritma',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Aljabar Linier',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Array',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Desain Basis Data',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Desain Tabel',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Distribusi Model',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'ER Model',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Flowchart',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Fungsi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Kalkulus',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Korelasi Koefisien',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Kurva Normal',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Logika',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Normalisasi Data',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Operasi Matriks',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Percabangan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Perulangan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Regresi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'SQL',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Statistik Deskriptif',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Trigonometrik',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Variabel',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Dasar",
                'bahankajian' => 'Vector',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'AWS Identity Management',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Cloud Computing Platforms',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],

            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Cloud Security',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],

            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Distributed Storage Systems',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],

            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Intents and Services',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Knowledge acquisition',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Knowledge Creation',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Knowledge engineering',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Knowledge management',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Knowledge technology',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Location Mobile Processing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Mobile Frameworks and Tools',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Mobile Storing and Retrieving Data',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Multimedia Mobile Programming',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Iptek Pendukung",
                'bahankajian' => 'Virtualization',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Analisa Data Berkala',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Analisis Multivariat',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Analisis Survival',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Analisis Time Series',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Big Data Architectures',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Big Data Design',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Big Data Tools',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Business Intelligence',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Classification',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Client Side',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Cluster Analysis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Clustering',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'CNN',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Collaborative Filtering',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Concept Learning',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Content-Based Recommendations',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Dashboard and Reporting',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Analysis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Association',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Exploration',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Integration',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Preprocessing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Transformation',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Data Warehousing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Deep Learning',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Distribusi Frekuensi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Distribusi Teoritis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Distributed Data Management',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Distributed Data Processing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Environmental Computing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Hadoop Eco System',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'HDFS',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Influence and Centrality',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Information Retrievals',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Keyword Searching',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Latent Factor Methods',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Lemmatization',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Manipulasi String',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Map Reduce',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Medical Minin',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Metrics and Evaluation',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Model Kerugian',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Multi Perceptron',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Neural Networks',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Operasi Teks',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Optimasi Cerdas',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Pencarian Ruang State',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Pengolahan Bahasa Alamiah',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Pengolahan Data',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Penyajian Data',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Personalization',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Phenomenology',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Prescriptive Analytics',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Representasi Pengetahuan',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Research Significance',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Retrieval Analysis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'RNN and LSTM',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Scientific Report',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Scoring',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Sentiment Analysis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Server Side',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Server Pakar',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'SOAP',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Social Media Analytics',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Social ties and information diffusion',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Socio-cultural Computing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Software Development Models',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Software Documentation',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Stream management and processing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Supervised Learning',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Technical Writing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Teori Keputusan Statistika',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Testing methodologies',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Tokenisasi',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Topic Analysis',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Uji Validitas dan Reliabilitas',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Ukuran Pemusatan dan dan Letak Data',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Unsupervised Learning',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'User Requirement',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'User-interface design',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Validation Model',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Vector Space Model',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Visualization Techniques',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Web Development Framework',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'Word Indexing',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'WSDL',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'rumpunkeilmuan' => "Rumpun Keilmuan Inti",
                'bahankajian' => 'YARN Architechture',
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],

        ]);
    }
}
